baseurl = "http://fbrx.github.io/"
languageCode = "en-us"
title = "// fBrx"
theme = "hugo-uno"
[Params]
    author = "fBrx"
    github = "fBrx"
    xing = "Florian_Bruessel"
    description = "fixing the world one exception at a time."
    about = "/page/about"
    cover = "/images/DSC_0667.jpg"
