baseurl = "https://fbrx.github.io/"
languageCode = "en-us"
title = "// Florian Brüssel / fBrx"
theme = "hugo-uno"

[Params]
    author = "fBrx"
    github = "fBrx"
    twitter = "f_brx"
    xing = "Florian_Bruessel"
    description = "...fixing the world, one exception at a time..."
    about = "/page/about"
    projects = "/project/#blog"
    cover = "/images/DSC_0667.jpg"
